const articles = [
  {
    name: 'building-this-blog',
    title: 'Building this Blog',
    content: [
      `Graveler nincada budew xurkitree pyroar octillery: murkrow grimer guzzlord venomoth torracat stakataka tornadus. Mareanie pyukumuku seismitoad panpour spheal wobbuffet magnemite grubbin, uxie shelmet tyranitar krokorok krookodile dwebble liepard litleo kakuna machamp. Torkoal weezing dwebble zebstrika charmander sneasel vulpix, gligar golett deino. Lunala sharpedo diggersby snover dialga jynx munchlax chespin corphish, spewpa cherubi cubchoo xerneas marowak vespiquen dugtrio geodude ledyba sigilyph. Delibird spinda persian mesprit litleo bastiodon skorupi phanpy golisopod. Deoxys staravia mankey throh. Weepinbell muk dustox, bounsweet prinplup piplup blastoise nidoran♀ milotic archeops tornadus azumarill pupitar. Steenee spinarak smoochum. Tapu koko cosmog kommo-o cosmog quagsire. Smeargle seismitoad hoothoot feebas mudbray pawniard furret chimecho skrelp, golbat gurdurr patrat brionne gourgeist totodile nihilego dragonite cloyster. Carnivine cacturne jumpluff aggron fraxure. Type: null floatzel roggenrola nidorino shellos conkeldurr misdreavus whiscash. Totodile natu amaura.`,
      `Silvally timburr clamperl happiny chingling porygon2 uxie, binacle zweilous geodude solgaleo salazzle celesteela golem. Parasect smoochum claydol lanturn toxicroak haunter hoothoot riolu silcoon. Pidgeot azumarill beartic girafarig porygon-z lunatone kricketune koffing steenee. Excadrill mareanie natu tyrunt rhyhorn groudon gardevoir escavalier numel solosis, keldeo gumshoos flareon lickitung scizor archeops. Empoleon slakoth qwilfish dialga throh swampert mareanie jynx rayquaza. Spoink rapidash quilava. Xerneas foongus tapu lele steenee regigigas nihilego poochyena keldeo pikachu jumpluff. Sandygast geodude seviper parasect primarina nidoran♀ jigglypuff yungoos spinarak, fennekin braixen rufflet togepi samurott roserade goodra scraggy lurantis. Solgaleo torkoal blaziken sylveon ponyta cubone. Butterfree zapdos gengar gumshoos carracosta torterra silcoon. Yanma gliscor taillow cofagrigus gyarados yamask fomantis. Kecleon keldeo shinx muk dragonair breloom cacnea registeel drifblim, togetic muk emboar mienfoo tangela basculin goodra. Altaria drifloon zoroark gible. Cradily nincada cyndaquil kricketune shellder sceptile charmander mothim, qwilfish murkrow nidorina archeops absol herdier simisage spritzee rayquaza. Bulbasaur magearna houndoom. Accelgor doduo shiftry musharna porygon.`,
    ],
  },
  {
    name: 'applying-for-jobs',
    title: 'Applying to Jobs in Tech',
    content: [
      `Graveler nincada budew xurkitree pyroar octillery: murkrow grimer guzzlord venomoth torracat stakataka tornadus. Mareanie pyukumuku seismitoad panpour spheal wobbuffet magnemite grubbin, uxie shelmet tyranitar krokorok krookodile dwebble liepard litleo kakuna machamp. Torkoal weezing dwebble zebstrika charmander sneasel vulpix, gligar golett deino. Lunala sharpedo diggersby snover dialga jynx munchlax chespin corphish, spewpa cherubi cubchoo xerneas marowak vespiquen dugtrio geodude ledyba sigilyph. Delibird spinda persian mesprit litleo bastiodon skorupi phanpy golisopod. Deoxys staravia mankey throh. Weepinbell muk dustox, bounsweet prinplup piplup blastoise nidoran♀ milotic archeops tornadus azumarill pupitar. Steenee spinarak smoochum. Tapu koko cosmog kommo-o cosmog quagsire. Smeargle seismitoad hoothoot feebas mudbray pawniard furret chimecho skrelp, golbat gurdurr patrat brionne gourgeist totodile nihilego dragonite cloyster. Carnivine cacturne jumpluff aggron fraxure. Type: null floatzel roggenrola nidorino shellos conkeldurr misdreavus whiscash. Totodile natu amaura.`,
      `Silvally timburr clamperl happiny chingling porygon2 uxie, binacle zweilous geodude solgaleo salazzle celesteela golem. Parasect smoochum claydol lanturn toxicroak haunter hoothoot riolu silcoon. Pidgeot azumarill beartic girafarig porygon-z lunatone kricketune koffing steenee. Excadrill mareanie natu tyrunt rhyhorn groudon gardevoir escavalier numel solosis, keldeo gumshoos flareon lickitung scizor archeops. Empoleon slakoth qwilfish dialga throh swampert mareanie jynx rayquaza. Spoink rapidash quilava. Xerneas foongus tapu lele steenee regigigas nihilego poochyena keldeo pikachu jumpluff. Sandygast geodude seviper parasect primarina nidoran♀ jigglypuff yungoos spinarak, fennekin braixen rufflet togepi samurott roserade goodra scraggy lurantis. Solgaleo torkoal blaziken sylveon ponyta cubone. Butterfree zapdos gengar gumshoos carracosta torterra silcoon. Yanma gliscor taillow cofagrigus gyarados yamask fomantis. Kecleon keldeo shinx muk dragonair breloom cacnea registeel drifblim, togetic muk emboar mienfoo tangela basculin goodra. Altaria drifloon zoroark gible. Cradily nincada cyndaquil kricketune shellder sceptile charmander mothim, qwilfish murkrow nidorina archeops absol herdier simisage spritzee rayquaza. Bulbasaur magearna houndoom. Accelgor doduo shiftry musharna porygon.`,
    ],
  },
  {
    name: 'studying-algos',
    title: 'Studying Algorithms',
    content: [
      `Graveler nincada budew xurkitree pyroar octillery: murkrow grimer guzzlord venomoth torracat stakataka tornadus. Mareanie pyukumuku seismitoad panpour spheal wobbuffet magnemite grubbin, uxie shelmet tyranitar krokorok krookodile dwebble liepard litleo kakuna machamp. Torkoal weezing dwebble zebstrika charmander sneasel vulpix, gligar golett deino. Lunala sharpedo diggersby snover dialga jynx munchlax chespin corphish, spewpa cherubi cubchoo xerneas marowak vespiquen dugtrio geodude ledyba sigilyph. Delibird spinda persian mesprit litleo bastiodon skorupi phanpy golisopod. Deoxys staravia mankey throh. Weepinbell muk dustox, bounsweet prinplup piplup blastoise nidoran♀ milotic archeops tornadus azumarill pupitar. Steenee spinarak smoochum. Tapu koko cosmog kommo-o cosmog quagsire. Smeargle seismitoad hoothoot feebas mudbray pawniard furret chimecho skrelp, golbat gurdurr patrat brionne gourgeist totodile nihilego dragonite cloyster. Carnivine cacturne jumpluff aggron fraxure. Type: null floatzel roggenrola nidorino shellos conkeldurr misdreavus whiscash. Totodile natu amaura.`,
      `Silvally timburr clamperl happiny chingling porygon2 uxie, binacle zweilous geodude solgaleo salazzle celesteela golem. Parasect smoochum claydol lanturn toxicroak haunter hoothoot riolu silcoon. Pidgeot azumarill beartic girafarig porygon-z lunatone kricketune koffing steenee. Excadrill mareanie natu tyrunt rhyhorn groudon gardevoir escavalier numel solosis, keldeo gumshoos flareon lickitung scizor archeops. Empoleon slakoth qwilfish dialga throh swampert mareanie jynx rayquaza. Spoink rapidash quilava. Xerneas foongus tapu lele steenee regigigas nihilego poochyena keldeo pikachu jumpluff. Sandygast geodude seviper parasect primarina nidoran♀ jigglypuff yungoos spinarak, fennekin braixen rufflet togepi samurott roserade goodra scraggy lurantis. Solgaleo torkoal blaziken sylveon ponyta cubone. Butterfree zapdos gengar gumshoos carracosta torterra silcoon. Yanma gliscor taillow cofagrigus gyarados yamask fomantis. Kecleon keldeo shinx muk dragonair breloom cacnea registeel drifblim, togetic muk emboar mienfoo tangela basculin goodra. Altaria drifloon zoroark gible. Cradily nincada cyndaquil kricketune shellder sceptile charmander mothim, qwilfish murkrow nidorina archeops absol herdier simisage spritzee rayquaza. Bulbasaur magearna houndoom. Accelgor doduo shiftry musharna porygon.`,
    ],
  },
]

export default articles
